version: '3'
services:
  sunhammer:
    build:
      context: ./
    command: sh -c "yarn && yarn storybook"
    ports:
      - '6006:6006'
      - '8080:8080'
    working_dir: /root/sunhammer
    volumes:
      - ./:/root/sunhammer
      - ./node_modules
    container_name: sunhammer
