name: Run Post Deploy script

on:
  push:
    branches: [master, staging]

jobs:
  pub-sub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Branch name GITHUB_REF_NAME
        run: echo running on branch ${GITHUB_REF_NAME}
      - name: Assigning branch name to environment variable
        run: echo "NEXT_PUBLIC_VERCEL_ENV=${GITHUB_REF_NAME,,}" >> $GITHUB_ENV
      - name: Post Deploy Script
        run: npm run post-deploy
        env:
          node-version: "16.x"
          FIREBASE_ADMIN_CLIENT_EMAIL: "${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}"
          FIREBASE_ADMIN_PRIVATE_KEY: "${{ secrets.FIREBASE_ADMIN_PRIVATE_KEY }}"
          FIREBASE_ADMIN_PRIVATE_KEY2: "${{ env.FIREBASE_ADMIN_PRIVATE_KEY }}"
          WEBSITE_ADDRESS: "${{ secrets.WEBSITE_ADDRESS }}"
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: "${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}"
          FIREBASE_ADMIN_CLIENT_EMAIL2: ${{secrets[format(env.NEXT_PUBLIC_VERCEL_ENV, '_FIREBASE_ADMIN_CLIENT_EMAIL')]}}
          FIREBASE_ADMIN_CLIENT_EMAIL3: ${{format(env.NEXT_PUBLIC_VERCEL_ENV, '_FIREBASE_ADMIN_CLIENT_EMAIL')}}
