name: Publish library to npm 

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install deps
        run: yarn
      - name: Build
        run: yarn build
        env:
          API_URL: https://ui.sunhammer.io
          LIBRARY_NAME: sunhammer-ui
          STORY_BOOK_URL: https://ui.sunhammer.io/
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}                    